// Sample Data for Navisol Boat Manufacturing System

import type { Article, BoatConfiguration } from './types';
import { generateId } from './formatting';

// Real Eagle Boats model groups for compatibility assignments
const SMALL_MODELS = ['Eagle 525T', 'Eagle C550', 'Eagle C570'];
const MEDIUM_MODELS = ['Eagle 25TS', 'Eagle C720', 'Eagle 28SG'];
const LARGE_MODELS = ['Eagle 28TS', 'Eagle C999', 'Eagle Hybruut 28'];
const FLAGSHIP_MODELS = ['Eagle 32TS'];
const ALL_MODELS = [...SMALL_MODELS, ...MEDIUM_MODELS, ...LARGE_MODELS, ...FLAGSHIP_MODELS];
const MEDIUM_AND_UP = [...MEDIUM_MODELS, ...LARGE_MODELS, ...FLAGSHIP_MODELS];
const LARGE_AND_UP = [...LARGE_MODELS, ...FLAGSHIP_MODELS];

export const SAMPLE_ARTICLES: Article[] = [
  // Hull & Structural Components
  {
    id: generateId(),
    part_name: 'Hull Plating Eagle 28TS',
    category: '1. Hull & Structural Components',
    subcategory: '1.1 Hull Construction',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-HULL-28TS',
    purchase_price_excl_vat: 8500,
    sales_price_excl_vat: 12500,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 5,
    min_stock_level: 2,
    parts_list_category: '1. Hull & Structural Components',
    parts_list_subcategory: '1.1 Hull Construction',
    boat_model_compat: ['Eagle 28TS'],
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Self-draining Cockpit System',
    category: '1. Hull & Structural Components',
    subcategory: '1.1 Hull Construction',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-SDC-001',
    purchase_price_excl_vat: 1200,
    sales_price_excl_vat: 1850,
    currency: 'EUR',
    quantity_unit: 'set',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 10,
    min_stock_level: 3,
    parts_list_category: '1. Hull & Structural Components',
    parts_list_subcategory: '1.1 Hull Construction',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Swim Platform Teak Finish',
    category: '1. Hull & Structural Components',
    subcategory: '1.3 Deck & Exterior Structure',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-SWIM-TK',
    purchase_price_excl_vat: 950,
    sales_price_excl_vat: 1450,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 8,
    min_stock_level: 2,
    parts_list_category: '1. Hull & Structural Components',
    parts_list_subcategory: '1.3 Deck & Exterior Structure',
    boat_model_compat: MEDIUM_AND_UP,
    standard_or_optional: 'Optional',
    price_calculation: 'fixed',
  },

  // Propulsion - Electric
  {
    id: generateId(),
    part_name: 'Electric Inboard Motor 15kW',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    brand: 'Torqeedo',
    manufacturer_article_no: 'TQ-CRUISE-15',
    supplier: 'Torqeedo GmbH',
    purchase_price_excl_vat: 12500,
    sales_price_excl_vat: 16500,
    currency: 'EUR',
    quantity_unit: 'pcs',
    voltage_power: '48V / 15 kW',
    electric_compatible: true,
    diesel_compatible: false,
    hybrid_compatible: true,
    stock_qty: 3,
    min_stock_level: 1,
    lead_time_days: 14,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    boat_model_compat: [...SMALL_MODELS, ...MEDIUM_MODELS],
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Electric Inboard Motor 20kW',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    brand: 'Torqeedo',
    manufacturer_article_no: 'TQ-CRUISE-20',
    supplier: 'Torqeedo GmbH',
    purchase_price_excl_vat: 16000,
    sales_price_excl_vat: 21500,
    currency: 'EUR',
    quantity_unit: 'pcs',
    voltage_power: '48V / 20 kW',
    electric_compatible: true,
    diesel_compatible: false,
    hybrid_compatible: true,
    stock_qty: 2,
    min_stock_level: 1,
    lead_time_days: 21,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    boat_model_compat: LARGE_AND_UP,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Battery Pack 400Ah 48V',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    brand: 'Victron Energy',
    manufacturer_article_no: 'VE-LFP-400',
    supplier: 'Victron Energy',
    purchase_price_excl_vat: 8500,
    sales_price_excl_vat: 11200,
    currency: 'EUR',
    quantity_unit: 'pcs',
    voltage_power: '48V / 400Ah',
    weight_kg: 145,
    electric_compatible: true,
    diesel_compatible: false,
    hybrid_compatible: true,
    stock_qty: 4,
    min_stock_level: 2,
    lead_time_days: 7,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },

  // Propulsion - Diesel
  {
    id: generateId(),
    part_name: 'Diesel Inboard Motor 30HP',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    brand: 'Vetus',
    manufacturer_article_no: 'VETUS-M3.29',
    supplier: 'Vetus Maxwell',
    purchase_price_excl_vat: 9800,
    sales_price_excl_vat: 13500,
    currency: 'EUR',
    quantity_unit: 'pcs',
    voltage_power: '30 HP / 22 kW',
    weight_kg: 165,
    electric_compatible: false,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 2,
    min_stock_level: 1,
    lead_time_days: 21,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    boat_model_compat: MEDIUM_AND_UP,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },

  // Hybrid components
  {
    id: generateId(),
    part_name: 'Hybrid Control Unit',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    brand: 'Bellmarine',
    manufacturer_article_no: 'BM-HCU-100',
    supplier: 'Bellmarine',
    purchase_price_excl_vat: 3500,
    sales_price_excl_vat: 4800,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: false,
    diesel_compatible: false,
    hybrid_compatible: true,
    stock_qty: 3,
    min_stock_level: 1,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    boat_model_compat: ['Eagle Hybruut 28', 'Eagle 28TS', 'Eagle 32TS'],
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Hybrid Clutch/Coupling',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    brand: 'ZF Marine',
    manufacturer_article_no: 'ZF-HYB-CLCH',
    supplier: 'ZF Marine',
    purchase_price_excl_vat: 2800,
    sales_price_excl_vat: 3950,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: false,
    diesel_compatible: false,
    hybrid_compatible: true,
    stock_qty: 2,
    min_stock_level: 1,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.1 Motorisation (Electric/Diesel/Hybrid)',
    boat_model_compat: ['Eagle Hybruut 28', 'Eagle 28TS', 'Eagle 32TS'],
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },

  // Propeller Shaft System
  {
    id: generateId(),
    part_name: 'Propeller Shaft 30mm Stainless',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.2 Propeller Shaft System',
    brand: 'Vetus',
    manufacturer_article_no: 'VETUS-SHAFT30',
    supplier: 'Vetus Maxwell',
    purchase_price_excl_vat: 420,
    sales_price_excl_vat: 650,
    currency: 'EUR',
    quantity_unit: 'pcs',
    dimensions_lxhxw_mm: '1500x30x30',
    material: 'Stainless Steel 316',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 6,
    min_stock_level: 2,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.2 Propeller Shaft System',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Propeller 4-Blade 16"',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.2 Propeller Shaft System',
    brand: 'Flexofold',
    manufacturer_article_no: 'FF-4B-16',
    supplier: 'Flexofold',
    purchase_price_excl_vat: 1850,
    sales_price_excl_vat: 2450,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 4,
    min_stock_level: 2,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.2 Propeller Shaft System',
    boat_model_compat: MEDIUM_AND_UP,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Rope Cutter Shaft Mount',
    category: '2. Propulsion & Drivetrain',
    subcategory: '2.2 Propeller Shaft System',
    brand: 'Spurs Marine',
    manufacturer_article_no: 'SPM-RC-30',
    supplier: 'Spurs Marine',
    purchase_price_excl_vat: 380,
    sales_price_excl_vat: 550,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 8,
    min_stock_level: 3,
    parts_list_category: '2. Propulsion & Drivetrain',
    parts_list_subcategory: '2.2 Propeller Shaft System',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Optional',
    price_calculation: 'fixed',
  },

  // Steering System
  {
    id: generateId(),
    part_name: 'Hydraulic Helm Pump',
    category: '3. Steering System',
    subcategory: '3.1 Hydraulic Steering',
    brand: 'Vetus',
    manufacturer_article_no: 'VETUS-HTP42',
    supplier: 'Vetus Maxwell',
    purchase_price_excl_vat: 890,
    sales_price_excl_vat: 1250,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 5,
    min_stock_level: 2,
    parts_list_category: '3. Steering System',
    parts_list_subcategory: '3.1 Hydraulic Steering',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Steering Wheel Chrome 380mm',
    category: '3. Steering System',
    subcategory: '3.2 Mechanical Components',
    brand: 'Ultraflex',
    manufacturer_article_no: 'UF-SW380-C',
    supplier: 'Ultraflex',
    purchase_price_excl_vat: 285,
    sales_price_excl_vat: 420,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 10,
    min_stock_level: 3,
    parts_list_category: '3. Steering System',
    parts_list_subcategory: '3.2 Mechanical Components',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },

  // Electrical System
  {
    id: generateId(),
    part_name: 'Navigation Light Set LED',
    category: '4. Electrical System & Navigation',
    subcategory: '4.2 Navigation & Communication',
    brand: 'Aqua Signal',
    manufacturer_article_no: 'AS-NAV-LED-SET',
    supplier: 'Aqua Signal',
    purchase_price_excl_vat: 320,
    sales_price_excl_vat: 485,
    currency: 'EUR',
    quantity_unit: 'set',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 12,
    min_stock_level: 4,
    parts_list_category: '4. Electrical System & Navigation',
    parts_list_subcategory: '4.2 Navigation & Communication',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'VHF Radio DSC Fixed Mount',
    category: '4. Electrical System & Navigation',
    subcategory: '4.2 Navigation & Communication',
    brand: 'Icom',
    manufacturer_article_no: 'ICOM-M510',
    supplier: 'Icom',
    purchase_price_excl_vat: 420,
    sales_price_excl_vat: 595,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 6,
    min_stock_level: 2,
    parts_list_category: '4. Electrical System & Navigation',
    parts_list_subcategory: '4.2 Navigation & Communication',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Optional',
    price_calculation: 'fixed',
  },

  // Bow Thruster
  {
    id: generateId(),
    part_name: 'Bow Thruster BOWPRO 57',
    category: '4. Electrical System & Navigation',
    subcategory: '4.5 Bow Thruster System',
    brand: 'Vetus',
    manufacturer_article_no: 'VETUS-BOWPRO57',
    supplier: 'Vetus Maxwell',
    purchase_price_excl_vat: 1200,
    sales_price_excl_vat: 2000,
    currency: 'EUR',
    quantity_unit: 'pcs',
    voltage_power: '12V / 2.2 kW',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 4,
    min_stock_level: 2,
    parts_list_category: '4. Electrical System & Navigation',
    parts_list_subcategory: '4.5 Bow Thruster System',
    boat_model_compat: MEDIUM_AND_UP,
    standard_or_optional: 'Optional',
    price_calculation: 'fixed',
  },

  // Deck Equipment
  {
    id: generateId(),
    part_name: 'Anchor Stainless Steel 10kg',
    category: '5. Deck Equipment & Comfort',
    subcategory: '5.1 Mooring & Anchoring',
    brand: 'Lewmar',
    manufacturer_article_no: 'LW-ANC-10SS',
    supplier: 'Lewmar',
    purchase_price_excl_vat: 185,
    sales_price_excl_vat: 275,
    currency: 'EUR',
    quantity_unit: 'pcs',
    weight_kg: 10,
    material: 'Stainless Steel 316',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 15,
    min_stock_level: 5,
    parts_list_category: '5. Deck Equipment & Comfort',
    parts_list_subcategory: '5.1 Mooring & Anchoring',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Bimini Top Canvas',
    category: '5. Deck Equipment & Comfort',
    subcategory: '5.5 Canvas & Covers',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-BIM-28TS',
    purchase_price_excl_vat: 1250,
    sales_price_excl_vat: 1850,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 6,
    min_stock_level: 2,
    parts_list_category: '5. Deck Equipment & Comfort',
    parts_list_subcategory: '5.5 Canvas & Covers',
    boat_model_compat: MEDIUM_AND_UP,
    standard_or_optional: 'Optional',
    price_calculation: 'fixed',
  },

  // Interior & Finishing
  {
    id: generateId(),
    part_name: 'Cushion Set Premium Marine',
    category: '6. Interior & Finishing',
    subcategory: '6.1 Seating & Upholstery',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-CUSH-PREM',
    purchase_price_excl_vat: 2200,
    sales_price_excl_vat: 3200,
    currency: 'EUR',
    quantity_unit: 'set',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 5,
    min_stock_level: 2,
    parts_list_category: '6. Interior & Finishing',
    parts_list_subcategory: '6.1 Seating & Upholstery',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Seadek Flooring Full Deck',
    category: '6. Interior & Finishing',
    subcategory: '6.2 Flooring & Surfaces',
    brand: 'SeaDek',
    manufacturer_article_no: 'SD-FULL-28TS',
    supplier: 'SeaDek Marine Products',
    purchase_price_excl_vat: 1800,
    sales_price_excl_vat: 2650,
    currency: 'EUR',
    quantity_unit: 'm²',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 8,
    min_stock_level: 2,
    parts_list_category: '6. Interior & Finishing',
    parts_list_subcategory: '6.2 Flooring & Surfaces',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Optional',
    price_calculation: 'fixed',
  },

  // Safety & Certification
  {
    id: generateId(),
    part_name: 'Fire Extinguisher 2kg ABC',
    category: '7. Safety & Certification',
    subcategory: '7.1 Safety Equipment',
    brand: 'Gloria',
    manufacturer_article_no: 'GLO-FE-2ABC',
    supplier: 'Gloria GmbH',
    purchase_price_excl_vat: 45,
    sales_price_excl_vat: 75,
    currency: 'EUR',
    quantity_unit: 'pcs',
    weight_kg: 3.5,
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 20,
    min_stock_level: 8,
    parts_list_category: '7. Safety & Certification',
    parts_list_subcategory: '7.1 Safety Equipment',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'CE Declaration & Documentation Package',
    category: '7. Safety & Certification',
    subcategory: '7.2 Certification & Documentation',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-CE-DOC',
    purchase_price_excl_vat: 450,
    sales_price_excl_vat: 650,
    currency: 'EUR',
    quantity_unit: 'set',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 50,
    min_stock_level: 10,
    parts_list_category: '7. Safety & Certification',
    parts_list_subcategory: '7.2 Certification & Documentation',
    boat_model_compat: ALL_MODELS,
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },

  // Project Costs
  {
    id: generateId(),
    part_name: 'Installation Labour',
    category: '9. Project & Operational Costs',
    subcategory: '9.1 Labour & Services',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-LABOUR',
    purchase_price_excl_vat: 65,
    sales_price_excl_vat: 85,
    currency: 'EUR',
    quantity_unit: 'hour',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 999,
    min_stock_level: 0,
    parts_list_category: '9. Project & Operational Costs',
    parts_list_subcategory: '9.1 Labour & Services',
    boat_model_compat: [...ALL_MODELS, 'Custom'],
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
  {
    id: generateId(),
    part_name: 'Commissioning & Sea Trial',
    category: '9. Project & Operational Costs',
    subcategory: '9.1 Labour & Services',
    brand: 'Navisol',
    manufacturer_article_no: 'NAV-COMM',
    purchase_price_excl_vat: 650,
    sales_price_excl_vat: 950,
    currency: 'EUR',
    quantity_unit: 'pcs',
    electric_compatible: true,
    diesel_compatible: true,
    hybrid_compatible: true,
    stock_qty: 999,
    min_stock_level: 0,
    parts_list_category: '9. Project & Operational Costs',
    parts_list_subcategory: '9.1 Labour & Services',
    boat_model_compat: [...ALL_MODELS, 'Custom'],
    standard_or_optional: 'Standard',
    price_calculation: 'fixed',
  },
];

// Get articles by propulsion compatibility
export function getArticlesForPropulsion(propulsion: 'Electric' | 'Diesel' | 'Hybrid' | 'Outboard', articles: Article[]): Article[] {
  return articles.filter(a => {
    if (propulsion === 'Electric') return a.electric_compatible;
    if (propulsion === 'Diesel') return a.diesel_compatible;
    if (propulsion === 'Hybrid') return a.hybrid_compatible;
    return true; // Outboard - return all
  });
}

// Get articles by boat model
export function getArticlesForBoatModel(model: string, articles: Article[]): Article[] {
  return articles.filter(a => a.boat_model_compat.some(m => m === model));
}

// Get articles by category
export function getArticlesByCategory(category: string, articles: Article[]): Article[] {
  return articles.filter(a => a.category === category);
}
